### ISSUE TITLE
Widget background shows my desktop background

### ISSUE THREAD

**Issue by p-himik** [berlam/awesome-switcher#12]
awesome v4.2-289-g98e5922
Ubuntu 18.04

With the default settings, the switcher looks like this on my machine:
![switcher](https://user-images.githubusercontent.com/4410314/40884667-621d629e-6742-11e8-9144-143fe413d394.png)

Is it intentional? If so, is there a way to make it a solid color?

**Comment by psliwka** [comment]
My guess is that it's looking that way because you don't have any X compositor running, so Awesome is forced to use fake transparency tricks. Try running [Compton](https://github.com/chjj/compton) or something.

**Comment by p-himik** [comment]
Not sure I follow. What transparency? Isn't the background supposed to be opaque?
Or you mean client preview transparency, and that it somehow influences the main widget background?

Update: it does indeed work with Compton.

**Comment by p-himik** [comment]
Ah, sorry, I'm blind - I just noticed that `preview_box_bg` is RGBA and not RGB. I'm just not used to seeing RGBA in this notation.
