### ISSUE TITLE
Nothing Shows Up When Pressing Alt + Tab

### ISSUE THREAD

**Issue by PedroSilva8** [berlam/awesome-switcher#14]
I followed all the steps of the README, i added the `local switcher = require("awesome-switcher")`
and the key bindings

```
awful.key({ altkey,           }, "Tab",
  function ()
      switcher.switch( 1, "Mod1", "Alt_L", "Shift", "Tab")
  end),

  awful.key({ altkey, "Shift"   }, "Tab",
  function ()
      switcher.switch(-1, "Mod1", "Alt_L", "Shift", "Tab")
  end),
```
But when i press Alt + Tab nothing shows up, if i remove the r in switcher in the keybinding when i press alt tab a error saying switch doesnt exist shows up, so i know alt tab is being detected and the switcher.switch is being executed.
Any idea how i can fix this?
This is my `awesome -v` info
```
awesome devel (Too long)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by berlam** [comment]
Have you installed libcairo and libcairo-gobject2 on your system?

**Comment by PedroSilva8** [comment]
I had this bug in solus since then i chaged to arch and i dont have this problem anymore.

**Comment by thepenguinthatwants** [comment]
> I had this bug in solus since then i chaged to arch and i dont have this problem anymore.

Does it still work? Wondering if the module is too old to work?
I've tried to get this work and using awesome 4.3-2

**Comment by berlam** [comment]
@thepenguinthatwants 

The module still works, I am actively using it currently.
