### ISSUE TITLE
Does this switcher work with awesome 4.3?

### ISSUE THREAD

**Issue by thepenguinthatwants** [berlam/awesome-switcher#16]
I've tried to get this work but it doesnt give any errors nor response.

**Comment by berlam** [comment]
@thepenguinthatwants 

Please post the output of `awesome -v` and check  if you have installed libcairo and libcairo-gobject2.

**Comment by thepenguinthatwants** [comment]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2


Okay seems like libcairo is not listed as it wasn't compiled with it? Otherwise I have 
this https://archlinux.org/packages/extra/x86_64/cairo/files/ installed

**Comment by thepenguinthatwants** [comment]
Seems like archlinux doesnt have aur or official packages for libcairo-gobject2
