### ISSUE TITLE
None of the running apps show when doing Alt + Tab

### ISSUE THREAD

**Issue by steve-todorov** [berlam/awesome-switcher#7]
I've been trying to figure out what's wrong for a while now but it seems I'm too "green" to awesome wm.

I've followed the tutorial and changed everything in the config files the same way as shown in the README. I've added the `local switcher = require("awesome-switcher-preview")` in the beginning, I've also added the key bindings exactly as shown in the tutorial. However the result is the following:

![20171013_045013](https://user-images.githubusercontent.com/2303663/31526862-24c7504e-afd2-11e7-96be-6c997984ac2b.jpg)

Doing alt + tab actually switches the windows but the previews are missing. Is there a dependency I need to have for this to work?

**Comment by berlam** [comment]
Looks to me as if you have not installed the cairo dependency, as text is also not shown.
Have you installed libcairo and libcairo-gobject2 on your system?

**Comment by steve-todorov** [comment]
@berlam thanks for replying. I also thought that and it appears I have the libcairo dependencies installed on my OpenSUSE:

```
zypper search -si libcairo
Loading repository data...
Reading installed packages...

S  | Name                    | Type    | Version    | Arch   | Repository             
---+-------------------------+---------+------------+--------+------------------------
i  | libcairo-gobject2       | package | 1.15.8-1.1 | x86_64 | openSUSE-Tumbleweed-Oss
i+ | libcairo-gobject2-32bit | package | 1.15.8-1.1 | x86_64 | openSUSE-Tumbleweed-Oss
i  | libcairo2               | package | 1.15.8-1.1 | x86_64 | openSUSE-Tumbleweed-Oss
i  | libcairo2-32bit         | package | 1.15.8-1.1 | x86_64 | openSUSE-Tumbleweed-Oss
i  | libcairomm-1_0-1        | package | 1.12.2-1.2 | x86_64 | openSUSE-Tumbleweed-Oss

```

Do I need a specific version?

**Comment by berlam** [comment]
Could you please try to start an xephyr session with you current setup and look for exception? It might be a problem with Lua 5.3 here.
```Shell
$ Xephyr :1 -ac -br -noreset -screen 1152x720 &
$ DISPLAY=:1.0 awesome -c ~/.config/awesome/rc.lua
```

**Comment by berlam** [comment]
@steve-todorov I just received a new build of awesomewm (with lua 5.3) from the debian testing channel. There are a few changes in lua 5.3, which break the plugin, but you might try out my [testing branch 'lua_module'](/berlam/awesome-switcher/tree/lua_module) for 5.3.

**Comment by psliwka** [comment]
For the record, I had the very same problem, and switching to lua_module branch resolved it.

@berlam, is there anything more to be done on this branch before merging it to master?

**Comment by berlam** [comment]
It seems to work for me and everyone else who had that issue. I think we can now safely merge it with master. Thank you for the reminder, @psliwka!
